### ISSUE TITLE
Implementation of High Pass Filter

### ISSUE THREAD

**Issue by dineshhops** [curiores/ArduinoTutorials#1]
Your explanations are very clear and impressive.

I am trying to implement high pass filter using the same method you mentioned. But I am not familier with the structure can you please guide on what value should i put here?``

`# Low-pass filter
w0 = 2*np.pi*5; # pole frequency (rad/s)
num = w0        # transfer function numerator coefficients
den = [1,w0]    # transfer function denominator coefficients
lowPass = signal.TransferFunction(num,den) # Transfer function`

I got that, I must have to made changes here but dont know what changes should i make to get it work for high pass filter.

**Comment by curiores** [comment]
Sorry that I missed this issue back in January. I implemented the high-pass version. 

Here's the high-pass version:
https://github.com/curiores/ArduinoTutorials/blob/main/BasicFilters/ArduinoImplementations/HighPass/HighPass.ino
with a few details about the derivation here:
https://github.com/curiores/ArduinoTutorials/tree/main/BasicFilters/Design/HighPass
